export const ARTICLE_GET_REQUEST = "ARTICLE_GET_REQUEST";
export const ARTICLE_POST_REQUEST = "ARTICLE_POST_REQUEST";
export const ARTICLE_PUT_REQUEST = "ARTICLE_PUT_REQUEST";
export const ARTICLE_DELETE_REQUEST = "ARTICLE_DELETE_REQUEST";
export const ARTICLE_SUCCESS = "ARTICLE_SUCCESS";
export const ARTICLE_FAILURE = "ARTICLE_FAILURE";
